### ISSUE TITLE
WHMCS UnsuspendModule

### ISSUE THREAD

**Issue by JakSar77** [wisp-gg/whmcs#4]
Hello,
when I send Unsuspend request via [WHMCS API](https://developers.whmcs.com/api-reference/moduleunsuspend/). 
Wisp api send suspend request. Can you fix it?
![image](https://user-images.githubusercontent.com/45877207/156844896-926265dd-73d1-45ce-8947-070216b2a02c.png)
![image](https://user-images.githubusercontent.com/45877207/156844929-19d91225-69ef-4590-b98b-a9d22d4d4690.png)
![image](https://user-images.githubusercontent.com/45877207/156844988-34fd6661-e59c-4d66-a963-b75feda29d4d.png)

Thank you

**Comment by TrixterTheTux** [comment]
The module already properly implements suspension and unsuspension (https://github.com/wisp-gg/whmcs/blob/master/wisp/wisp.php#L420-L446). This sounds more like a WHMCS API issue itself as the module only implements functions that WHMCS calls, which we have no control over.
